### ISSUE TITLE
Conversion Error : WINAPI

### ISSUE THREAD

**Issue by ochafik** [nativelibs4java/nativelibs4java#149]
hello, i am getting the below error in the generated native declaration "Conversion Error : WINAPI"

native declaration : D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\LScanEssentialsApi.h:693
Conversion Error : WINAPI

native declaration : D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\LScanEssentialsApi.h:709
Conversion Error : WINAPI

D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\LScanEssentialsApi.h:728
Conversion Error : WINAPI
...etc

java -jar jnaerator-0.9.4.jar -preferJavac  -direct -beanStructs -package com.crossmatch.lscan -library LScanEssentials D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\ImageData.h D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\LScanEssentialsApi_defs.h D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\LScanEssentialsApi_err.h D:\SaM\Projects\mcgeorgeconsulting\crossmatch\API\LScanEssentialsApi.h

moreover when i check my DLL file i see the "@" symbol at the end of each method declaration that is causing "java.lang.UnsatisfiedLinkError: Error looking up function" for all of the converted methods.

any ideas how to make a workaround?

I attached the header files

thanks

Google Code Info:
Issue #: 70
Author: sameeh.h...@gmail.com
Created On: 2010-08-07T11:02:10.000Z
Closed On:

**Comment by eludebebe** [comment]
Hello Dear,
I was working in a project where we have to integrate with this device and unfortunately the all header files stated in the SDK documentation are missing. Last time you have attached but the link is not working now, can you please share those file incase you have it. It is very crucial for my project. 
If you are also successful with the integration some help regarding it will be nice.
