### ISSUE TITLE
Can't find Windows.h

### ISSUE THREAD

**Issue by ochafik** [nativelibs4java/nativelibs4java#162]
Trying to run JNAerator and for some reason it can't find Windows.h.

I can't find a support mail list or other emails, so I'm opening an issue.

Attached is the batch file that I'm using to run JNAerator, and a file with the output.

I have verified that Windows.h is in the SDK include directory which is specified in the batch file, but it cannot seem to find it.

How can I further diagnose this issue?  As a result of this, I have some undefined types in my output, such as:

```
    /// Undefined type
    public static interface LPBYTE {

    };
    /// Undefined type
    public static interface LPWORD {

    };
    /// Undefined type
    public static interface LPVOID {

    };
    /// Undefined type
    public static interface LPSTR {

    };
```

Google Code Info:
Issue #: 87
Author: dudeh...@gmail.com
Created On: 2011-06-05T05:12:03.000Z
Closed On: 2011-06-17T10:32:46.000Z

**Comment by magick93** [comment]
I managed to get passed this error by using:

`"-IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include\Windows.h"`

Neither
`"-IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include\"`

nor

`"-IC:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include\*"` worked
