### ISSUE TITLE
Functions with __stdcall identifier are not generated - JNaerator

### ISSUE THREAD

**Issue by purijatin** [nativelibs4java/nativelibs4java#379]
From JNAerator version 9.10 and so, I have observe that it doesn't generate wrapper for functions defined with __stdcall. For example, for:

__stdcall EdsError EdsGetDeviceInfo(EdsCameraRef, EdsDeviceInfo*)

In the JNaerator 9.8, it was generated to 

NativeLong EdsGetDeviceInfo(EdSdkLibrary.__EdsObject inCameraRef, EdsDeviceInfo outDeviceInfo);

But nothing is generated in the later versions. This is observed commonly in all functions that contain __stdcall identifier.

**Comment by GreatGarlic** [comment]
@purijatin Why close  Issues? question solve?
