### ISSUE TITLE
Enhance JNAerator to support BridJ @Library dependencies declaration

### ISSUE THREAD

**Issue by bp-alex** [nativelibs4java/nativelibs4java#535]
I'm using JNAerator to generate BridJ bindings to some shared libraries. While BridJ offers [dependent library support](https://code.google.com/p/bridj/wiki/LibrariesLookup#Dependent_libraries) there doesn't appear to be a way to cause JNAerator to use this feature. Given I am using the [maven-jnaerator-plugin](https://code.google.com/p/jnaerator/wiki/Maven#Maven_JNAerator_Plugin), the Java bindings are generated as part of each build in `target/generated-sources/java`. I've worked around the issue by adding an `exec-maven-plugin` that uses `sed` to edit the JNAerator-written `.java` source code and edit the `@Library` annotation to include a `dependencies` value. However this makes the build operating system dependent and it would cleaner if JNAerator could support this. Someone else also asked about this in the [JNAerator FAQ](https://code.google.com/p/jnaerator/wiki/JNAeratorFAQ):

> Comment by rlhage...@gmail.com, May 3, 2013
> Thanks for the awesome work! Is there a way to auto generate the following annotation with JNAerator?
> 
> @Library("MainLib?", dependencies = { "Dependency1", "Dependency2"... })

**Comment by davidekholm** [comment]
This -dependencies flag seems to be just what I need as my "raw.dll" native library (LibRaw project) on Windows depends on the files msvcp140.dll and vcruntime140.dll. I've listed all three DLLs  and added the following -dependencies flag: -library raw -dependencies msvcp140,vcruntime140 but it doesn't work unless I manually put the files vcruntime140.dll and msvcp140.dll in WINDOWS\System32 for instance. 
Any clue as to what I'm doing wrong?
